FROM jandebleser/openport-distribution-tmp


RUN cd / ; git clone https://github.com/pyinstaller/pyinstaller.git
RUN cd /pyinstaller/bootloader && \
    git reset --hard v3.6
RUN cd /pyinstaller/bootloader && \
	python waf all && \ 
	cd .. && \
	python setup.py install



#    sed -i '/.*Werror.*/d' wscript && \
#    cd .. && \

#    python ./waf configure build install --no-lsb && \
#    cd .. && \
#    python setup.py install
