FROM golang:1.14-stretch
LABEL os=linux
LABEL arch=arm64

ENV GOOS=linux
ENV GOARCH=arm64
ENV CGO_ENABLED=1
#ENV CC=arm-linux-gnueabi-gcc
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
#ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig

# install build & runtime dependencies
RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && dpkg --configure -a \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        upx \
        gcc-aarch64-linux-gnu \
        libc6-dev-arm64-cross \
        pkg-config \
        curl \
    && rm -rf /var/lib/apt/lists/*

COPY go.mod \
    go.sum \
    /apps/go/

WORKDIR /apps/go/

ENV GO_ARCH=arm64
ENV CC=aarch64-linux-gnu-gcc
ENV CC_FOR_TARGET=aarch64-linux-gnu-gcc
RUN go mod download

COPY main.go /apps/go/
RUN go build -o openport-arm64 main.go
