FROM ubuntu:16.04
MAINTAINER JanDeBleser

ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y software-properties-common wget gcc curl
RUN wget https://go.dev/dl/go1.23.1.linux-amd64.tar.gz && \
    rm -rf /usr/local/go &&  \
    tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /apps/go/

ENV OPENPORT_EXE=/openport-amd64
RUN go version
RUN wget https://github.com/gotestyourself/gotestsum/releases/download/v1.11.0/gotestsum_1.11.0_linux_amd64.tar.gz && \
    tar -xf gotestsum*.gz && \
    mv gotestsum /usr/bin

COPY src/go.mod \
    src/go.sum \
    /apps/go/
RUN go mod download

COPY src/ /apps/go/

RUN go build -ldflags "-s -w" -tags netgo -o /openport-amd64 apps/openport/main.go
