version: '3'
services:
  client_tests:
    build:
      context: "."
      dockerfile: Dockerfile-amd64
    command: sh -c "/openport-amd64 register ${KEY_REGISTRATION_TOKEN} --server https://test.openport.io && gotestsum --format standard-verbose --junitfile /apps/go/test-results/report.xml apps/openport/*.go"
    user: "${UID}:${GID}"
    volumes:
      - ./test-results:/apps/go/test-results/
      - ./test-results:/root/.openport/
  # // for debugging only
#      - ./src/:/apps/go/src/
