FROM debian:buster
# Using the oldest version of debian that supplies the armhf architecture. Ubuntu 16.04 does not support armhf.

MAINTAINER JanDeBleser

RUN apt-get update && apt-get install -y software-properties-common wget gcc curl
RUN wget https://go.dev/dl/go1.23.1.linux-amd64.tar.gz && \
    rm -rf /usr/local/go &&  \
    tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

LABEL os=linux
LABEL arch=armhf

ENV GOOS=linux
ENV GOARCH=arm
ENV GOARM=7
ENV CGO_ENABLED=1
ENV CC=arm-linux-gnueabihf-gcc
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig

# install build & runtime dependencies
RUN dpkg --add-architecture armhf \
    && apt-get update \
    && dpkg --configure -a \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        upx \
        libc6-dev-armhf-cross \
   gcc-arm-linux-gnueabihf \
        pkg-config curl \
    && rm -rf /var/lib/apt/lists/*

COPY src/go.mod \
    src/go.sum \
    /apps/go/

WORKDIR /apps/go/

RUN go mod download

COPY src/ /apps/go/
RUN go build -ldflags "-s -w -extldflags=-static" -tags netgo -o /openport-armhf apps/openport/main.go
