FROM debian:buster
# Using the oldest version of debian that supplies the arm64 architecture. Ubuntu 16.04 does not support armhf.
MAINTAINER JanDeBleser

# buster is out of LFS, we need to use the archive repos
RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list
RUN sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list
RUN sed -i '/buster-updates/d' /etc/apt/sources.list

RUN apt-get update && apt-get install -y software-properties-common wget gcc curl
RUN wget https://go.dev/dl/go1.25.7.linux-amd64.tar.gz && \
    rm -rf /usr/local/go &&  \
    tar -C /usr/local -xzf go1.25.7.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

LABEL os=linux
LABEL arch=arm64

ENV GOOS=linux
ENV GOARCH=arm64
ENV CGO_ENABLED=1
#ENV CC=arm-linux-gnueabi-gcc
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
#ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig

# install build & runtime dependencies
RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && dpkg --configure -a \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        upx \
        gcc-aarch64-linux-gnu \
        libc6-dev-arm64-cross \
        pkg-config \
        curl \
    && rm -rf /var/lib/apt/lists/*

COPY src/go.mod \
    src/go.sum \
    /apps/go/

WORKDIR /apps/go/

ENV GO_ARCH=arm64
ENV CC=aarch64-linux-gnu-gcc
ENV CC_FOR_TARGET=aarch64-linux-gnu-gcc
RUN go mod download

COPY src/ /apps/go/
RUN go build -ldflags "-s -w -extldflags=-static" -tags netgo -o /openport-arm64 apps/openport/main.go
