FROM ubuntu:18.04
MAINTAINER JanDeBleser

ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:longsleep/golang-backports
RUN apt-get update && apt-get install -y golang-1.14-go git

WORKDIR /apps/go/

ENV PATH=$PATH:/usr/lib/go-1.14/bin
ENV GOBIN=$GOPATH/bin
ENV OPENPORT_EXE=/apps/go/openport-amd64
RUN go version
RUN go get gotest.tools/gotestsum

COPY src/go.mod \
    src/go.sum \
    /apps/go/
RUN go mod download

COPY src/ /apps/go/

RUN go build -o openport-amd64 main.go
