FROM ubuntu:16.04
MAINTAINER JanDeBleser

RUN apt-get update && apt-get install -y software-properties-common wget gcc curl
RUN wget https://go.dev/dl/go1.25.7.linux-amd64.tar.gz && \
    rm -rf /usr/local/go &&  \
    tar -C /usr/local -xzf go1.25.7.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

LABEL os=linux
LABEL arch=armv6

ENV GOOS=linux
ENV GOARCH=arm
ENV CGO_ENABLED=1
ENV CC=arm-linux-gnueabi-gcc
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig

# install build & runtime dependencies
RUN dpkg --add-architecture arm \
    && apt-get update \
    && dpkg --configure -a \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        upx \
        gcc-arm-linux-gnueabi \
        libc6-dev-armel-cross \
        pkg-config curl \
    && rm -rf /var/lib/apt/lists/*

COPY src/go.mod \
    src/go.sum \
    /apps/go/

WORKDIR /apps/go/

ENV GOARM=6

RUN go mod download

COPY src/ /apps/go/
RUN go build -ldflags "-s -w -extldflags=-static" -tags netgo -o /openport-armv6 apps/openport/main.go
