FROM golang:1.21.5-bullseye
LABEL os=linux
LABEL arch=armv6

ENV GOOS=linux
ENV GOARCH=arm
ENV CGO_ENABLED=1
ENV CC=arm-linux-gnueabi-gcc
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig

# install build & runtime dependencies
RUN dpkg --add-architecture arm \
    && apt-get update \
    && dpkg --configure -a \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        upx \
        gcc-arm-linux-gnueabi \
        libc6-dev-armel-cross \
        pkg-config curl \
    && rm -rf /var/lib/apt/lists/*

COPY src/go.mod \
    src/go.sum \
    /apps/go/

WORKDIR /apps/go/

ENV GOARM=6

RUN go mod download

COPY src/ /apps/go/
RUN go build -ldflags "-s -w -extldflags=-static" -o /openport-armv6-static apps/openport/main.go
