# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "shell", inline: <<-SHELL
      sudo dpkg -i /vagrant/openport*.deb
      openport 22 -R -d
  SHELL
end
