# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"  # 16.04
 # config.vm.box = "ubuntu/bionic64"  #  18.04
  config.vm.provision "shell", inline: <<-SHELL
      sudo dpkg -i /vagrant/openport*.deb
      openport 22 -R -d
  SHELL

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.network :forwarded_port, guest: 22, host: 12343

end
