Vagrant.configure("2") do |config|
  config.vm.box = "danimaetrix/windows-8.1"
  config.vm.box_version = "1.0"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provision "shell", path: "provision.ps1"

end