version: '3'

services:
  openport-go:
    image: openport-go-amd64
    networks:
      - no-internet
    command: ./openport-amd64 22 --proxy=socks5h://proxy-no-pass:1080 --verbose
    # command: curl --socks5 socks5h://proxy-no-pass:1080 http://ifcfg.co
    depends_on:
      - proxy-no-pass

  proxy-no-pass:
    image: serjs/go-socks5-proxy
    networks:
      - no-internet
      - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
